1. Data Preprocessing

In [ ]:
import pandas as pd
import numpy as np

Load the Dataset

In [ ]:
# reading csv files
data =  pd.read_csv('breast-cancer-wisconsin.data', sep = ',', na_values="?")
d1 = np.array(data)
col = ['Sample code number', 'Clump Thickness', 'Uniformity of Cell Size', 'Uniformity of Cell Shape', 'Marginal Adhesion', 'Single Epithelial Cell Size', 'Bare Nuclei', 'Bland Chromatin', 'Normal Nucleoli', 'Mitoses', 'Class']
df = pd.DataFrame(data=d1, columns=col)
print(df)

     Sample code number  Clump Thickness  Uniformity of Cell Size  \
0             1002945.0              5.0                      4.0   
1             1015425.0              3.0                      1.0   
2             1016277.0              6.0                      8.0   
3             1017023.0              4.0                      1.0   
4             1017122.0              8.0                     10.0   
..                  ...              ...                      ...   
693            776715.0              3.0                      1.0   
694            841769.0              2.0                      1.0   
695            888820.0              5.0                     10.0   
696            897471.0              4.0                      8.0   
697            897471.0              4.0                      8.0   

     Uniformity of Cell Shape  Marginal Adhesion  Single Epithelial Cell Size  \
0                         4.0                5.0                          7.0   
1        

Check and replace the null values.

In [ ]:
df.isnull().sum()

Sample code number              0
Clump Thickness                 0
Uniformity of Cell Size         0
Uniformity of Cell Shape        0
Marginal Adhesion               0
Single Epithelial Cell Size     0
Bare Nuclei                    16
Bland Chromatin                 0
Normal Nucleoli                 0
Mitoses                         0
Class                           0
dtype: int64

In [ ]:
df['Bare Nuclei'] = df['Bare Nuclei'].replace(np.NaN, df['Bare Nuclei'].mean())

In [ ]:
df.isnull().sum()

Sample code number             0
Clump Thickness                0
Uniformity of Cell Size        0
Uniformity of Cell Shape       0
Marginal Adhesion              0
Single Epithelial Cell Size    0
Bare Nuclei                    0
Bland Chromatin                0
Normal Nucleoli                0
Mitoses                        0
Class                          0
dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 698 entries, 0 to 697
Data columns (total 11 columns):
 #   Column                       Non-Null Count  Dtype  
---  ------                       --------------  -----  
 0   Sample code number           698 non-null    float64
 1   Clump Thickness              698 non-null    float64
 2   Uniformity of Cell Size      698 non-null    float64
 3   Uniformity of Cell Shape     698 non-null    float64
 4   Marginal Adhesion            698 non-null    float64
 5   Single Epithelial Cell Size  698 non-null    float64
 6   Bare Nuclei                  698 non-null    float64
 7   Bland Chromatin              698 non-null    float64
 8   Normal Nucleoli              698 non-null    float64
 9   Mitoses                      698 non-null    float64
 10  Class                        698 non-null    float64
dtypes: float64(11)
memory usage: 60.1 KB


In [ ]:
df.head()

Sample code number  Clump Thickness  Uniformity of Cell Size  \
0           1002945.0              5.0                      4.0   
1           1015425.0              3.0                      1.0   
2           1016277.0              6.0                      8.0   
3           1017023.0              4.0                      1.0   
4           1017122.0              8.0                     10.0   

   Uniformity of Cell Shape  Marginal Adhesion  Single Epithelial Cell Size  \
0                       4.0                5.0                          7.0   
1                       1.0                1.0                          2.0   
2                       8.0                1.0                          3.0   
3                       1.0                3.0                          2.0   
4                      10.0                8.0                          7.0   

   Bare Nuclei  Bland Chromatin  Normal Nucleoli  Mitoses  Class  
0         10.0              3.0              2.0      1.0    2.0  
1          2.0              3.0              1.0      1.0    2.0  
2          4.0              3.0              7.0      1.0    2.0  
3          1.0              3.0              1.0      1.0    2.0  
4         10.0              9.0              7.0      1.0    4.0

Split the Dataset into x and y

In [ ]:
x = pd.DataFrame(df.iloc[:, 1:9].values)
y = df.iloc[:, 9].values

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [ ]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [ ]:
print(type(x_train), type(x_test))

<class 'numpy.ndarray'> <class 'numpy.ndarray'>


2. Build Artificial Neural Network

In [ ]:
import keras
from keras.models import Sequential
from keras.layers import Dense

# Initialize the ANN
model = Sequential()

#Add the input layer and the first hidden layer
model.add(Dense(units = 6, activation = 'relu', input_dim = 8))

#Add the second hidden layer
model.add(Dense(units = 6, activation = 'relu'))

#Add the output layer
model.add(Dense(units = 1, activation = 'sigmoid'))

In [ ]:
'''import keras
from keras.models import Sequential
from keras.layers import Dense

model = keras.Sequential([keras.layers.Dense(3, input_shape=(8,), activation ='relu'), 
                          keras.layers.Dense(3, activation = 'relu'), 
                          keras.layers.Dense(1, activation = 'sigmoid')])'''

"import keras\nfrom keras.models import Sequential\nfrom keras.layers import Dense\n\nmodel = keras.Sequential([keras.layers.Dense(3, input_shape=(8,), activation ='relu'), \n                          keras.layers.Dense(3, activation = 'relu'), \n                          keras.layers.Dense(1, activation = 'sigmoid')])"


3. Train the ANN

Compile the ANN

In [ ]:
model.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

Adam is the optimizer that can perform stochastic gradient descent. The main purpose of gradient descent is to minimize the cost function. The cost function is nothing but a method to find out the error between the actual output and the predicted output.

Fit the ANN to the training set

In [ ]:
model.fit(x_train, y_train, epochs=5, batch_size=10)

Epoch 1/5
56/56 [==============================] - 1s 2ms/step - loss: 0.8143 - accuracy: 0.4391
Epoch 2/5
56/56 [==============================] - 0s 2ms/step - loss: 0.5696 - accuracy: 0.8011
Epoch 3/5
56/56 [==============================] - 0s 2ms/step - loss: 0.3393 - accuracy: 0.8369
Epoch 4/5
56/56 [==============================] - 0s 2ms/step - loss: 0.0489 - accuracy: 0.8387
Epoch 5/5
56/56 [==============================] - 0s 2ms/step - loss: -0.3694 - accuracy: 0.8387


Predicting the Test Result

In [ ]:
y_pred = model.predict(x_test)
y_pred = (y_pred > 0.5)

5/5 [==============================] - 0s 2ms/step


In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score

cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[110   0   0   0   0   0   0   0   0]
 [ 13   0   0   0   0   0   0   0   0]
 [  4   0   0   0   0   0   0   0   0]
 [  2   0   0   0   0   0   0   0   0]
 [  1   0   0   0   0   0   0   0   0]
 [  1   0   0   0   0   0   0   0   0]
 [  3   0   0   0   0   0   0   0   0]
 [  4   0   0   0   0   0   0   0   0]
 [  2   0   0   0   0   0   0   0   0]]


0.7857142857142857